# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /blog/:categories/:year/:month/:day/:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://kyleoliveira.github.io
baseurl:
title: Kyle Oliveira
author: Kyle Oliveira
description: Personal blog and resume
avatar: kyle_and_wren_at_robert_treman.jpg #profile.png
email: kcoliveira@ucdavis.edu
github: kyleoliveira # username
twitter: TheKyleOliveira
linkedin: kcoliveira
# stackoverflow: username   #e.g: users/2735833/proton1h1
# disqus: username
# google_analytics: UA-69391421-1

# needed for travis-ci build
exclude: [vendor]

collections:
  recipes:
    output: true
    permalink: /:collection/:title.html
  leadership:
    output: true
    permalink: /:collection/:title.html
